"""initial repository schema

Revision ID: f3df869a3e7c
Revises:
Created: 2026-08-26 12:01:59.391844
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f3df869a3e7c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum("APT", "RPM", name="repositorytype", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("root_path", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("retention_count", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=200), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column("deregistered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "retention_count >= 0", name=op.f("ck_repository_retention_count_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository")),
    )
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repository_slug"), ["slug"], unique=True)

    op.create_table(
        "apt_distribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("codename", sa.String(length=100), nullable=False),
        sa.Column("suite", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_apt_distribution_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apt_distribution")),
        sa.UniqueConstraint(
            "repository_id", "codename", name=op.f("uq_apt_distribution_repository_id")
        ),
    )
    with op.batch_alter_table("apt_distribution", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apt_distribution_repository_id"), ["repository_id"], unique=False
        )

    op.create_table(
        "rpm_variant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("arch", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_rpm_variant_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rpm_variant")),
        sa.UniqueConstraint(
            "repository_id", "name", "arch", name=op.f("uq_rpm_variant_repository_id")
        ),
    )
    with op.batch_alter_table("rpm_variant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rpm_variant_repository_id"), ["repository_id"], unique=False
        )

    op.create_table(
        "apt_architecture",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribution_id"],
            ["apt_distribution.id"],
            name=op.f("fk_apt_architecture_distribution_id_apt_distribution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apt_architecture")),
        sa.UniqueConstraint(
            "distribution_id", "name", name=op.f("uq_apt_architecture_distribution_id")
        ),
    )
    with op.batch_alter_table("apt_architecture", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apt_architecture_distribution_id"), ["distribution_id"], unique=False
        )

    op.create_table(
        "apt_component",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribution_id"],
            ["apt_distribution.id"],
            name=op.f("fk_apt_component_distribution_id_apt_distribution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apt_component")),
        sa.UniqueConstraint(
            "distribution_id", "name", name=op.f("uq_apt_component_distribution_id")
        ),
    )
    with op.batch_alter_table("apt_component", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apt_component_distribution_id"), ["distribution_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("apt_component", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apt_component_distribution_id"))

    op.drop_table("apt_component")
    with op.batch_alter_table("apt_architecture", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apt_architecture_distribution_id"))

    op.drop_table("apt_architecture")
    with op.batch_alter_table("rpm_variant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rpm_variant_repository_id"))

    op.drop_table("rpm_variant")
    with op.batch_alter_table("apt_distribution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apt_distribution_repository_id"))

    op.drop_table("apt_distribution")
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_slug"))

    op.drop_table("repository")
    # ### end Alembic commands ###
