"""sessions, roles and the audit log

Revision ID: 0f380d8c0af9
Revises: f6be3c27a290
Created: 2026-08-27 08:32:53.503145
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0f380d8c0af9"
down_revision: str | None = "f6be3c27a290"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_dn", sa.String(length=512), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("MAINTAINER", "ADMIN", name="role", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("csrf_secret", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revalidate_after", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_session_token_hash")),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index("ix_session_expires_at", ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_session_user_dn"), ["user_dn"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=512), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum("USER", "TOKEN", "SYSTEM", name="actortype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN",
                "LOGOUT",
                "SESSION_REVALIDATED",
                "REPOSITORY_CREATE",
                "DISTRIBUTION_ADD",
                "KEY_GENERATE",
                "KEY_IMPORT",
                "KEY_DELETE",
                "PACKAGE_UPLOAD",
                "PACKAGE_REMOVE",
                "REGENERATE",
                name="auditaction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "SUCCESS", "FAILURE", "DENIED", name="auditoutcome", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("repository_id", sa.Integer(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column(
            "details_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_audit_log_repository_id_repository"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_actor_occurred", ["actor", "occurred_at"], unique=False)
        batch_op.create_index("ix_audit_log_occurred_at", ["occurred_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_repository_id"), ["repository_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_repository_id"))
        batch_op.drop_index("ix_audit_log_occurred_at")
        batch_op.drop_index("ix_audit_log_actor_occurred")

    op.drop_table("audit_log")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_user_dn"))
        batch_op.drop_index("ix_session_expires_at")

    op.drop_table("session")
    # ### end Alembic commands ###
