"""api tokens

Revision ID: 47677915d873
Revises: 0f380d8c0af9
Created: 2026-08-28 21:28:31.370622
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "47677915d873"
down_revision: str | None = "0f380d8c0af9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_dn", sa.String(length=512), nullable=False),
        sa.Column("owner_username", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("prefix", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.String(length=120), nullable=False),
        sa.Column("repository_scope", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_token_token_hash")),
    )
    with op.batch_alter_table("api_token", schema=None) as batch_op:
        batch_op.create_index(
            "ix_api_token_owner_created", ["owner_dn", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_api_token_owner_dn"), ["owner_dn"], unique=False)
        batch_op.create_index("ix_api_token_prefix", ["prefix"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_token", schema=None) as batch_op:
        batch_op.drop_index("ix_api_token_prefix")
        batch_op.drop_index(batch_op.f("ix_api_token_owner_dn"))
        batch_op.drop_index("ix_api_token_owner_created")

    op.drop_table("api_token")
    # ### end Alembic commands ###
