"""apt packages, signing keys and jobs

Revision ID: f6be3c27a290
Revises: f3df869a3e7c
Created: 2026-08-26 16:44:19.730976
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f6be3c27a290"
down_revision: str | None = "f3df869a3e7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signing_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=40), nullable=False),
        sa.Column(
            "algorithm",
            sa.Enum(
                "RSA4096", "RSA3072", "ED25519", name="keyalgorithm", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("uid", sa.Text(), nullable=False),
        sa.Column("public_key_armored", sa.Text(), nullable=False),
        sa.Column("passphrase_ref", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signing_key")),
    )
    with op.batch_alter_table("signing_key", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signing_key_fingerprint"), ["fingerprint"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_signing_key_name"), ["name"], unique=True)

    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("REGENERATE_METADATA", name="jobtype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("repository_id", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="jobstate",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("log", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_job_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_repository_id"), ["repository_id"], unique=False)
        batch_op.create_index("ix_job_state_repository", ["state", "repository_id"], unique=False)

    op.create_table(
        "package",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=200), nullable=False),
        sa.Column("release", sa.String(length=200), nullable=True),
        sa.Column("architecture", sa.String(length=32), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "control_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by", sa.Text(), nullable=True),
        sa.Column(
            "uploaded_via",
            sa.Enum("WEB", "TOKEN", "IMPORT", name="uploadsource", native_enum=False, length=8),
            nullable=False,
        ),
        sa.CheckConstraint("size >= 0", name=op.f("ck_package_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_package_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package")),
        sa.UniqueConstraint("repository_id", "relative_path", name="uq_package_repository_path"),
    )
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_package_architecture"), ["architecture"], unique=False)
        batch_op.create_index(batch_op.f("ix_package_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_package_repository_id"), ["repository_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_package_sha256"), ["sha256"], unique=False)

    op.create_table(
        "package_publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(component_id IS NOT NULL) <> (variant_id IS NOT NULL)",
            name=op.f("ck_package_publication_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["apt_component.id"],
            name=op.f("fk_package_publication_component_id_apt_component"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["package.id"],
            name=op.f("fk_package_publication_package_id_package"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["rpm_variant.id"],
            name=op.f("fk_package_publication_variant_id_rpm_variant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_publication")),
        sa.UniqueConstraint("package_id", "component_id", name="uq_publication_component"),
        sa.UniqueConstraint("package_id", "variant_id", name="uq_publication_variant"),
    )
    with op.batch_alter_table("package_publication", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_package_publication_component_id"), ["component_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_package_publication_package_id"), ["package_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_package_publication_variant_id"), ["variant_id"], unique=False
        )

    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.add_column(sa.Column("signing_key_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_repository_signing_key_id"), ["signing_key_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_repository_signing_key_id_signing_key"),
            "signing_key",
            ["signing_key_id"],
            ["id"],
            ondelete="RESTRICT",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_repository_signing_key_id_signing_key"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_repository_signing_key_id"))
        batch_op.drop_column("signing_key_id")

    with op.batch_alter_table("package_publication", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_package_publication_variant_id"))
        batch_op.drop_index(batch_op.f("ix_package_publication_package_id"))
        batch_op.drop_index(batch_op.f("ix_package_publication_component_id"))

    op.drop_table("package_publication")
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_package_sha256"))
        batch_op.drop_index(batch_op.f("ix_package_repository_id"))
        batch_op.drop_index(batch_op.f("ix_package_name"))
        batch_op.drop_index(batch_op.f("ix_package_architecture"))

    op.drop_table("package")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_state_repository")
        batch_op.drop_index(batch_op.f("ix_job_repository_id"))

    op.drop_table("job")
    with op.batch_alter_table("signing_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signing_key_name"))
        batch_op.drop_index(batch_op.f("ix_signing_key_fingerprint"))

    op.drop_table("signing_key")
    # ### end Alembic commands ###
